// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMT2Zpmm1VNAOJnywo7TbMIYTdy01c6A',
    appId: '1:114598193397:web:a72809e984396e5c2ffdbc',
    messagingSenderId: '114598193397',
    projectId: 'fatimah-app2',
    authDomain: 'fatimah-app2.firebaseapp.com',
    databaseURL: 'https://fatimah-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app2.firebasestorage.app',
    measurementId: 'G-TKDW4CS4KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWf6gKCmdV-4pCSKSR6fn23VPKWyVFPA',
    appId: '1:114598193397:android:92e73f694e96f8a32ffdbc',
    messagingSenderId: '114598193397',
    projectId: 'fatimah-app2',
    databaseURL: 'https://fatimah-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpUR-4m4Xz4qjJFxe718k1POkkn72U4w',
    appId: '1:114598193397:ios:6fa2d44a8369fab02ffdbc',
    messagingSenderId: '114598193397',
    projectId: 'fatimah-app2',
    databaseURL: 'https://fatimah-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app2.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpUR-4m4Xz4qjJFxe718k1POkkn72U4w',
    appId: '1:114598193397:ios:6fa2d44a8369fab02ffdbc',
    messagingSenderId: '114598193397',
    projectId: 'fatimah-app2',
    databaseURL: 'https://fatimah-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app2.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGMT2Zpmm1VNAOJnywo7TbMIYTdy01c6A',
    appId: '1:114598193397:web:368b5317f148fda92ffdbc',
    messagingSenderId: '114598193397',
    projectId: 'fatimah-app2',
    authDomain: 'fatimah-app2.firebaseapp.com',
    databaseURL: 'https://fatimah-app2-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app2.firebasestorage.app',
    measurementId: 'G-XMGQ9D5PX4',
  );

}