// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJVnEfnN46Hzh1QCLulCl6y5okryeM8g',
    appId: '1:381908478328:web:ef1de54836ba8d1195408d',
    messagingSenderId: '381908478328',
    projectId: 'fatimah-app',
    authDomain: 'fatimah-app.firebaseapp.com',
    databaseURL: 'https://fatimah-app-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app.firebasestorage.app',
    measurementId: 'G-KDW0XPBE5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXi2-9bpr8sTlyNVQHQ1FKe1W058srsk',
    appId: '1:381908478328:android:d693455cfe4fff3a95408d',
    messagingSenderId: '381908478328',
    projectId: 'fatimah-app',
    databaseURL: 'https://fatimah-app-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVRzn5Z5psNJHwQ4dMRtm0qaeG8gf9fE',
    appId: '1:381908478328:ios:171de437ef6c06cc95408d',
    messagingSenderId: '381908478328',
    projectId: 'fatimah-app',
    databaseURL: 'https://fatimah-app-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhVRzn5Z5psNJHwQ4dMRtm0qaeG8gf9fE',
    appId: '1:381908478328:ios:171de437ef6c06cc95408d',
    messagingSenderId: '381908478328',
    projectId: 'fatimah-app',
    databaseURL: 'https://fatimah-app-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnJVnEfnN46Hzh1QCLulCl6y5okryeM8g',
    appId: '1:381908478328:web:99951b49c0cc2caa95408d',
    messagingSenderId: '381908478328',
    projectId: 'fatimah-app',
    authDomain: 'fatimah-app.firebaseapp.com',
    databaseURL: 'https://fatimah-app-default-rtdb.firebaseio.com',
    storageBucket: 'fatimah-app.firebasestorage.app',
    measurementId: 'G-9C6MY9C5D4',
  );

}